name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -C apps/web build
      - run: pnpm -C apps/web test:run || true
      - run: pnpm -C apps/server install || pnpm -C apps/server i
      - run: pnpm -C apps/server build

  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Build server image
        run: docker build -t sheets-server:ci ./apps/server
      - name: Scan image (placeholder)
        run: echo "Add Trivy/Grype scan here" && true